/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const NetworkNetworkIdLazyImport = createFileRoute('/network/$networkId')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const NetworkNetworkIdLazyRoute = NetworkNetworkIdLazyImport.update({
  id: '/network/$networkId',
  path: '/network/$networkId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/network/$networkId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/network/$networkId': {
      id: '/network/$networkId'
      path: '/network/$networkId'
      fullPath: '/network/$networkId'
      preLoaderRoute: typeof NetworkNetworkIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/network/$networkId': typeof NetworkNetworkIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/network/$networkId': typeof NetworkNetworkIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/network/$networkId': typeof NetworkNetworkIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/network/$networkId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/network/$networkId'
  id: '__root__' | '/' | '/network/$networkId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  NetworkNetworkIdLazyRoute: typeof NetworkNetworkIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  NetworkNetworkIdLazyRoute: NetworkNetworkIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/network/$networkId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/network/$networkId": {
      "filePath": "network/$networkId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
