/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const NetworkNetworkIdLazyRouteImport = createFileRoute('/network/$networkId')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const NetworkNetworkIdLazyRoute = NetworkNetworkIdLazyRouteImport.update({
  id: '/network/$networkId',
  path: '/network/$networkId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/network/$networkId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/network/$networkId': typeof NetworkNetworkIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/network/$networkId': typeof NetworkNetworkIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/network/$networkId': typeof NetworkNetworkIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/network/$networkId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/network/$networkId'
  id: '__root__' | '/' | '/network/$networkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  NetworkNetworkIdLazyRoute: typeof NetworkNetworkIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/$networkId': {
      id: '/network/$networkId'
      path: '/network/$networkId'
      fullPath: '/network/$networkId'
      preLoaderRoute: typeof NetworkNetworkIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  NetworkNetworkIdLazyRoute: NetworkNetworkIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
